# Generated by Django 2.2.7 on 2020-02-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afl_user', '0002_auto_20200211_0522'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsletter',
            table='newsletter',
        ),
    ]
