# Generated by Django 2.2.7 on 2020-02-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afl_user', '0003_auto_20200211_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phoneno', models.CharField(max_length=12, unique=True)),
                ('msg', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
