# Generated by Django 2.2.7 on 2020-02-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afl_user', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='msg',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phoneno',
            field=models.CharField(max_length=12),
        ),
    ]
