# Generated by Django 2.2.7 on 2020-02-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afl_user', '0005_auto_20200213_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
