# Generated by Django 2.2.7 on 2020-02-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afl_user', '0006_auto_20200214_0432'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='Country',
        ),
        migrations.AlterModelTable(
            name='state',
            table='State',
        ),
    ]
