# Generated by Django 2.2.7 on 2020-02-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afl_user', '0007_auto_20200214_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
